accepted = [
    "BSD-3-Clause-No-Military-License",
    "BSD-3-Clause",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "BSD-2-Clause",
    "Zlib",
    "Unicode-DFS-2016",
    "MPL-2.0"
]
